language: node_js
node_js:
  - "10"
  - "12"

script:
  - "npm run test"

jobs:
  include:
    - language: node_js
      node_js: node
      script:
        - nyc npm run test
      after_success: "npm run coveralls"
    - language: node_js
      name: types-check
      node_js: node
      script:
        - "npm run types-check"
    - language: node_js
      name: lint
      node_js: node
      script:
        - npm run lint
