language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "node"

jobs:
  include:
    - language: node_js
      node_js: 6
      script: "npm run no-koa-test"
    - language: node_js
      script:
        - "npm run test"
    - language: node_js
      node_js: node
      script:
        - "npm run types-check"
    - language: node_js
      node_js: node
      after_success: "npm run coveralls"
