version: 2.1
orbs:
  node: circleci/node@3.0.0

executors:
  current:
    docker:
      - image: node:current-alpine
  lts:
    docker:
      - image: node:lts-alpine
  active:
    docker:
      - image: node:12-alpine
  maintenance:
    docker:
      - image: node:10-alpine

jobs:
  node-test:
    parameters:
      node-version:
        type: executor
    executor: << parameters.node-version >>
    steps:
      - checkout
      - run: npm ci
      - run: npx nyc npm test
      - persist_to_workspace:
          root: .
          paths:
            - "coverage"
  prom-client-test:
    parameters:
      node-version:
        type: executor
      prom-client-version:
        type: string
    executor: << parameters.node-version >>
    steps:
      - checkout
      - run: npm ci
      - run: npm i prom-client@<< parameters.prom-client-version >>
      - run: npm test
  coverage:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm i coveralls
      - run: npm run coveralls
  types-check:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run: npm ci
      - run: npm run types-check
  lint-check:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

workflows:
  node-tests:
    jobs:
      - node-test:
          matrix:
            parameters:
              node-version: [current, lts, active, maintenance]
      - coverage:
          requires:
            - node-test-lts
  prom-client-tests:
    jobs:
      - prom-client-test:
          matrix:
            parameters:
              node-version: [lts, maintenance] 
              prom-client-version: ["12"]
  quality:
    jobs:
      - types-check
      - lint-check