name: CI

on: [ push, pull_request ]

jobs:
  lockfile-lint:
    name: Lockfile lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: lint lock file
        run: npx lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https

  quality-checks:
    needs: [ 'lockfile-lint' ]
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: types check
        run: npm run types-check
      - name: lint check
        run: npm run lint

  test:
    strategy:
      matrix:
        node: [ '10', '12', '14', '16' ]
    needs: [ 'quality-checks' ]
    name: Node v.${{ matrix.node }} Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.node }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: unit tests
        run: npm run unit-tests
      - name: integration tests
        run: npm run integration-tests
      - name: coveralls
        uses: coverallsapp/github-action@master
        if: ${{ matrix.node == '16' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  prom-client-test:
    strategy:
      matrix:
        prom-client: [ '12', '13', '14', '15', '16' ]
    needs: [ 'lockfile-lint', 'quality-checks' ]
    name: Prom Client v.${{ matrix.prom-client }} Tests (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: install prom client
        run: npm i prom-client@${{ matrix.prom-client }}
      - name: run tests
        run: npm test
